name: well_formed_demo_app
description: How to use the Well-Formed package effectively.

publish_to: "none"

version: 1.0.0
homepage: https://dartoos.dev
repository: https://github.com/dartoos-dev/well_formed

environment:
  sdk: ^3.5.0

dependencies:
  eo_color: ^2.2.0
  flutter:
    sdk: flutter
  well_formed:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.1

flutter:
  uses-material-design: true
