name: well_formed
description: A form field package designed to relieve developers of much of the form-related coding. It provides field masking, validation, smart trimming, and more.
version: 0.3.0
homepage: https://dartoos.dev
repository: https://github.com/dartoos-dev/well_formed

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  formdator: ^0.10.0
  mask_text_input_formatter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
